package directive

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/decred/dcrd/dcrec/secp256k1/v4"
	"github.com/decred/dcrd/dcrec/secp256k1/v4/ecdsa"
)

// --- cross-language agreement -------------------------------------------
//
// The fixtures are generated by the PYTHON implementation
// (backend/services/network_directive.py) and checked here. This is the test
// that actually matters: the two sides sign and verify the same bytes, and if
// they ever disagree the symptom is "your signature is invalid" on a node
// during an incident -- the worst possible place to discover a formatting
// difference. Regenerate with the snippet in backend/tests, do not hand-edit.

type fixture struct {
	Directive struct {
		Kind          string `json:"kind"`
		Sequence      uint64 `json:"sequence"`
		IssuedAt      int64  `json:"issued_at"`
		NotBefore     int64  `json:"not_before"`
		Emergency     bool   `json:"emergency"`
		OriginDomain  string `json:"origin_domain"`
		OriginAddress string `json:"origin_address"`
		OriginKey     string `json:"origin_key"`
		Note          string `json:"note"`
	} `json:"directive"`
	Canonical string `json:"canonical"`
}

func loadFixtures(t *testing.T) map[string]fixture {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("testdata", "canonical_fixtures.json"))
	if err != nil {
		t.Fatalf("fixtures: %v", err)
	}
	var out map[string]fixture
	if err := json.Unmarshal(body, &out); err != nil {
		t.Fatalf("fixtures: %v", err)
	}
	if len(out) == 0 {
		t.Fatal("fixtures are empty")
	}
	return out
}

func TestCanonicalMatchesPython(t *testing.T) {
	for name, f := range loadFixtures(t) {
		t.Run(name, func(t *testing.T) {
			d := &Directive{
				Kind: f.Directive.Kind, Sequence: f.Directive.Sequence,
				IssuedAt: f.Directive.IssuedAt, NotBefore: f.Directive.NotBefore,
				Emergency: f.Directive.Emergency, OriginDomain: f.Directive.OriginDomain,
				OriginAddress: f.Directive.OriginAddress, OriginKey: f.Directive.OriginKey,
				Note: f.Directive.Note,
			}
			if got := Canonical(d); got != f.Canonical {
				t.Fatalf("canonical mismatch\n go: %q\n py: %q", got, f.Canonical)
			}
		})
	}
}

func TestParsePythonCanonical(t *testing.T) {
	for name, f := range loadFixtures(t) {
		t.Run(name, func(t *testing.T) {
			d, err := ParseCanonical(f.Canonical)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if d.Kind != f.Directive.Kind || d.Sequence != f.Directive.Sequence {
				t.Fatalf("round trip lost fields: %+v", d)
			}
			if d.OriginDomain != f.Directive.OriginDomain {
				t.Fatalf("domain %q want %q", d.OriginDomain, f.Directive.OriginDomain)
			}
			if d.Emergency != f.Directive.Emergency {
				t.Fatalf("emergency %v want %v", d.Emergency, f.Directive.Emergency)
			}
			if Canonical(d) != f.Canonical {
				t.Fatal("re-rendering the parsed directive changed it")
			}
		})
	}
}

func TestANoteCannotForgeAField(t *testing.T) {
	// The one free-text field. A note reading "origin_domain: evil.example"
	// looks like a field; it must stay inside the note's value.
	f, ok := loadFixtures(t)["note_that_looks_like_a_field"]
	if !ok {
		t.Skip("fixture missing")
	}
	d, err := ParseCanonical(f.Canonical)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if d.OriginDomain != "syndichan.net" {
		t.Fatalf("note captured origin_domain: %q", d.OriginDomain)
	}
	if d.Emergency {
		t.Fatal("note turned on emergency")
	}
}

func TestMalformedMessagesAreRefused(t *testing.T) {
	good := Canonical(&Directive{Kind: KindMove, Sequence: 1, OriginDomain: "a.example"})
	cases := map[string]string{
		"empty":       "",
		"wrong header": "something else\n" + good,
		"truncated":   good[:len(good)-10],
		"extra line":  good + "\norigin_domain: evil.example",
	}
	for name, text := range cases {
		t.Run(name, func(t *testing.T) {
			if _, err := ParseCanonical(text); err == nil {
				t.Fatal("expected a refusal")
			}
		})
	}
}

// --- signatures ----------------------------------------------------------

// signPersonal produces an EIP-191 signature the way a wallet would, so the
// recovery path is exercised end to end rather than against a hand-built blob.
func signPersonal(t *testing.T, key *secp256k1.PrivateKey, message string) string {
	t.Helper()
	compact := ecdsa.SignCompact(key, personalHash(message), false)
	// decred emits [v+27]||r||s; Ethereum wants r||s||v.
	sig := make([]byte, 65)
	copy(sig, compact[1:])
	sig[64] = compact[0] - 27 + 27
	return "0x" + hex.EncodeToString(sig)
}

func TestRecoverSignerRoundTrip(t *testing.T) {
	key, err := secp256k1.GeneratePrivateKey()
	if err != nil {
		t.Fatal(err)
	}
	want := addressOf(key.PubKey())
	message := Canonical(&Directive{Kind: KindMove, Sequence: 5, OriginDomain: "a.example"})

	got, err := RecoverSigner(message, signPersonal(t, key, message))
	if err != nil {
		t.Fatalf("recover: %v", err)
	}
	if !SameAddress(got, want) {
		t.Fatalf("recovered %s want %s", got, want)
	}
}

func TestASingleAlteredByteChangesTheSigner(t *testing.T) {
	// The property the whole scheme rests on: a directive cannot be edited in
	// flight without the recovered address ceasing to be the pinned one.
	key, err := secp256k1.GeneratePrivateKey()
	if err != nil {
		t.Fatal(err)
	}
	original := &Directive{Kind: KindMove, Sequence: 5, OriginDomain: "good.example"}
	message := Canonical(original)
	sig := signPersonal(t, key, message)
	pinned := addressOf(key.PubKey())

	tampered := *original
	tampered.OriginDomain = "evil.example"
	got, err := RecoverSigner(Canonical(&tampered), sig)
	if err != nil {
		return // refusing outright is also correct
	}
	if SameAddress(got, pinned) {
		t.Fatal("a changed domain still recovered the pinned wallet")
	}
}

func TestRecoveryIdEncodings(t *testing.T) {
	// Wallets emit v as 27/28; some libraries emit 0/1. Rejecting the latter
	// would fail for signatures that are perfectly valid.
	key, err := secp256k1.GeneratePrivateKey()
	if err != nil {
		t.Fatal(err)
	}
	message := "hello"
	sig := signPersonal(t, key, message)
	raw, _ := hex.DecodeString(sig[2:])

	for _, v := range []byte{raw[64], raw[64] - 27} {
		alt := make([]byte, 65)
		copy(alt, raw[:64])
		alt[64] = v
		got, err := RecoverSigner(message, "0x"+hex.EncodeToString(alt))
		if err != nil {
			t.Fatalf("v=%d: %v", v, err)
		}
		if !SameAddress(got, addressOf(key.PubKey())) {
			t.Fatalf("v=%d recovered the wrong address", v)
		}
	}
}

func TestGarbageSignatures(t *testing.T) {
	message := "hello"
	for name, sig := range map[string]string{
		"empty":     "",
		"not hex":   "0xzzzz",
		"too short": "0x1234",
		"too long":  "0x" + hex.EncodeToString(make([]byte, 66)),
		"bad v":     "0x" + hex.EncodeToString(append(make([]byte, 64), 9)),
	} {
		t.Run(name, func(t *testing.T) {
			if _, err := RecoverSigner(message, sig); err == nil {
				t.Fatal("expected a refusal")
			}
		})
	}
}

// --- the rules a valid signature still has to pass ------------------------

func TestVerifyRequiresThePinnedWallet(t *testing.T) {
	key, _ := secp256k1.GeneratePrivateKey()
	other, _ := secp256k1.GeneratePrivateKey()
	d := &Directive{Kind: KindMove, Sequence: 2, OriginDomain: "a.example"}
	doc := &Document{Directive: d, Canonical: Canonical(d),
		Signature: signPersonal(t, key, Canonical(d))}

	if _, err := Verify(doc, addressOf(key.PubKey()), nil); err != nil {
		t.Fatalf("correct wallet: %v", err)
	}
	if _, err := Verify(doc, addressOf(other.PubKey()), nil); !errors.Is(err, ErrWrongWallet) {
		t.Fatalf("wrong wallet: got %v", err)
	}
	// An unset pin must never accept anything -- that is a node with no
	// configured authority following whoever speaks first.
	if _, err := Verify(doc, "", nil); err == nil {
		t.Fatal("an empty pinned wallet accepted a directive")
	}
}

func TestVerifyRefusesTextThatDisagreesWithItsFields(t *testing.T) {
	// A document carrying canonical text different from its own fields would
	// otherwise let one valid signature vouch for values nobody signed.
	key, _ := secp256k1.GeneratePrivateKey()
	real := &Directive{Kind: KindMove, Sequence: 2, OriginDomain: "good.example"}
	lie := &Directive{Kind: KindMove, Sequence: 2, OriginDomain: "evil.example"}
	doc := &Document{
		Directive: lie,
		Canonical: Canonical(real),
		Signature: signPersonal(t, key, Canonical(real)),
	}
	if _, err := Verify(doc, addressOf(key.PubKey()), nil); err == nil {
		t.Fatal("accepted fields the signature does not cover")
	}
}

func TestStaleAndFrozen(t *testing.T) {
	held := &Directive{Kind: KindMove, Sequence: 7}
	for _, seq := range []uint64{1, 6, 7} {
		if err := CheckAcceptable(&Directive{Kind: KindMove, Sequence: seq}, held); !errors.Is(err, ErrStale) {
			t.Fatalf("sequence %d was not refused: %v", seq, err)
		}
	}
	if err := CheckAcceptable(&Directive{Kind: KindMove, Sequence: 8}, held); err != nil {
		t.Fatalf("moving forward: %v", err)
	}

	frozen := &Directive{Kind: KindFreeze, Sequence: 7}
	if err := CheckAcceptable(&Directive{Kind: KindMove, Sequence: 8}, frozen); !errors.Is(err, ErrFrozen) {
		t.Fatalf("a freeze did not block a move: %v", err)
	}
	if err := CheckAcceptable(&Directive{Kind: KindResume, Sequence: 8}, frozen); err != nil {
		t.Fatalf("resume should lift a freeze: %v", err)
	}
	// A captured resume must not unfreeze a network frozen on purpose.
	if err := CheckAcceptable(&Directive{Kind: KindResume, Sequence: 5}, frozen); !errors.Is(err, ErrStale) {
		t.Fatalf("a stale resume was accepted: %v", err)
	}
}

func TestEffectiveHonoursTheDelay(t *testing.T) {
	ordinary := &Directive{Kind: KindMove, Sequence: 1, NotBefore: 1000}
	if ordinary.Effective(999) {
		t.Fatal("acted before not_before")
	}
	if !ordinary.Effective(1000) {
		t.Fatal("refused at exactly not_before")
	}
	emergency := &Directive{Kind: KindMove, Sequence: 1, NotBefore: 500, Emergency: true}
	if !emergency.Effective(500) {
		t.Fatal("an emergency directive waited")
	}
}
