package channel

// The browser and the node must agree — roadmap P8.
//
// state_test.go proves this package's encoding matches the CONTRACT, and
// proof-of-facilitation/browser-test proves the JavaScript matches the same
// vectors. Neither proves the two live implementations agree with each other
// over the actual wire shape, which is the thing that breaks in production: a
// browser signs a state, encodes it, sends it, and this node decodes it,
// re-derives the digest and recovers the signer. A disagreement anywhere along
// that path is a payment the node rejects after the user has already approved
// it — and the failure surfaces as "bad signature", which points at the wrong
// place entirely.
//
// So the fixture is generated by the real browser client, and verified here by
// the real node code. Nothing in this file computes an expected value: it
// checks that the JavaScript's digest is the digest this package derives from
// the JavaScript's own wire encoding.
//
// Skips when node or the ethers install is absent — an environment without
// them can still run the rest of the suite, and the golden vectors already
// hold each side to the contract independently.

import (
	"encoding/hex"
	"encoding/json"
	"math/big"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

type browserFixture struct {
	ChainID   int64  `json:"chain_id"`
	Contract  string `json:"contract"`
	Tipper    string `json:"tipper"`
	Recipient string `json:"recipient"`
	ChannelID string `json:"channel_id"`
	TipperIsA bool   `json:"tipper_is_a"`
	Cases     []struct {
		Name   string      `json:"name"`
		State  storedState `json:"state"`
		Digest string      `json:"digest"`
		Sig    string      `json:"sig"`
	} `json:"cases"`
}

func loadBrowserFixture(t *testing.T) browserFixture {
	t.Helper()

	node, err := exec.LookPath("node")
	if err != nil {
		t.Skip("node is not installed; the golden vectors still hold both sides to the contract")
	}
	root, err := filepath.Abs(filepath.Join("..", "..", "..", "proof-of-facilitation"))
	if err != nil {
		t.Fatalf("resolve repo root: %v", err)
	}
	script := filepath.Join(root, "browser-test", "sign-fixture.mjs")
	if _, err := os.Stat(script); err != nil {
		t.Skipf("browser fixture script missing: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "node_modules", "ethers")); err != nil {
		t.Skip("ethers is not installed in proof-of-facilitation; run npm install there")
	}

	cmd := exec.Command(node, script)
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		var stderr string
		if ee, ok := err.(*exec.ExitError); ok {
			stderr = string(ee.Stderr)
		}
		t.Fatalf("sign-fixture.mjs failed: %v\n%s", err, stderr)
	}

	var fx browserFixture
	if err := json.Unmarshal(out, &fx); err != nil {
		t.Fatalf("fixture is not JSON: %v", err)
	}
	if len(fx.Cases) == 0 {
		t.Fatal("fixture carried no cases")
	}
	return fx
}

// The channel id is where the party-ordering trap lives. If the two sides
// derived it differently they would not even be discussing the same channel.
func TestBrowserDerivesTheSameChannelID(t *testing.T) {
	fx := loadBrowserFixture(t)

	got := DeriveChannelID(mustAddr(t, fx.Tipper), mustAddr(t, fx.Recipient))
	if hexOf(got[:]) != strings.TrimPrefix(fx.ChannelID, "0x") {
		t.Fatalf("channel id\n browser %s\n node    %s", fx.ChannelID, hexOf(got[:]))
	}

	// And the browser's idea of which side it is must match this package's.
	a, _ := SortParties(mustAddr(t, fx.Tipper), mustAddr(t, fx.Recipient))
	if isA := a == mustAddr(t, fx.Tipper); isA != fx.TipperIsA {
		t.Errorf("party ordering disagrees: browser says tipperIsA=%v, node says %v",
			fx.TipperIsA, isA)
	}
}

// The whole loop: decode what the browser sent, re-derive the digest from the
// decoded state, and recover the signer. This is exactly what a node does with
// an incoming STATE_PROPOSE.
func TestBrowserSignedStatesVerifyHere(t *testing.T) {
	fx := loadBrowserFixture(t)
	contract := mustAddr(t, fx.Contract)
	tipper := mustAddr(t, fx.Tipper)
	chainID := big.NewInt(fx.ChainID)

	for _, tc := range fx.Cases {
		t.Run(tc.Name, func(t *testing.T) {
			state, err := decodeStateWire(tc.State)
			if err != nil {
				t.Fatalf("the node cannot decode what the browser sent: %v", err)
			}

			digest := StateDigest(chainID, contract, state.Channel, state.Nonce,
				state.BalanceA, state.BalanceB, state.HTLCRoot(),
				state.WithdrawA, state.WithdrawB)

			if hexOf(digest[:]) != strings.TrimPrefix(tc.Digest, "0x") {
				t.Fatalf("digest disagrees\n browser %s\n node    %s", tc.Digest, hexOf(digest[:]))
			}

			sig, err := hex.DecodeString(strings.TrimPrefix(tc.Sig, "0x"))
			if err != nil {
				t.Fatalf("signature is not hex: %v", err)
			}
			signer, err := RecoverSigner(digest, sig)
			if err != nil {
				t.Fatalf("the node cannot recover the browser's signature: %v", err)
			}
			if signer != tipper {
				t.Errorf("signature recovers to %s, expected the tipper %s", signer, tipper)
			}
		})
	}
}

// The case that motivated the wire fix: a checkpoint carries withdrawals, they
// are inside the digest, and they have to survive the trip.
func TestBrowserCheckpointKeepsItsWithdrawal(t *testing.T) {
	fx := loadBrowserFixture(t)

	for _, tc := range fx.Cases {
		if tc.Name != "checkpoint" {
			continue
		}
		state, err := decodeStateWire(tc.State)
		if err != nil {
			t.Fatalf("decode: %v", err)
		}
		total := new(big.Int).Add(orZero(state.WithdrawA), orZero(state.WithdrawB))
		if total.Sign() == 0 {
			t.Fatal("the checkpoint arrived with no withdrawal: the wire dropped it")
		}
		return
	}
	t.Fatal("the fixture has no checkpoint case")
}
